fix

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -40,17 +40,28 @@ jobs:
       - name: Prepare Build Environment
         run: |
           cd "$SDK_DL_DIR"
+          # 下载 sha256sums 文件并过滤出需要的行
           if ! ( wget -q -O - "$SDK_URL_PATH/sha256sums" | grep -- "$SDK_NAME" > sha256sums.small 2>/dev/null ) ; then
             echo "Can not find ${SDK_NAME} file in sha256sums."
             exit 1
           fi
+          # 解析出文件名
           SDK_FILE="$(cat sha256sums.small | cut -d' ' -f2 | sed 's/*//g')"
+          echo "SDK_FILE: $SDK_FILE"  # 调试信息
+          # 下载 SDK 文件
           wget -q -O "$SDK_FILE" "$SDK_URL_PATH/$SDK_FILE"
+          # 检查文件是否下载成功
+          if [ ! -f "$SDK_FILE" ]; then
+            echo "Failed to download SDK file: $SDK_FILE"
+            exit 1
+          fi
+          # 验证文件的完整性
           if ! sha256sum -c ./sha256sums.small >/dev/null 2>&1 ; then
             echo "SDK can not be verified!"
             exit 1
           fi
-          tar -Jxf "$SDK_DL_DIR/$SDK_FILE" -C "$SDK_HOME" --strip=1
+          # 解压 SDK 文件
+          tar -xf "$SDK_DL_DIR/$SDK_FILE" -C "$SDK_HOME" --strip=1
           
       - name: Build Packages
         run: |
